AllCops:
  Exclude:
    - 'db/schema.rb'
    - '**/*.jbuilder'
Metrics/LineLength:
  Max: 120
SpaceInsideHashLiteralBraces:
  Enabled: false
SpaceInsideBrackets:
  Enabled: false
Documentation:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
